# Generated by Django 4.1.3 on 2023-01-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_owner_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='pic',
        ),
    ]
