# Generated by Django 4.1.3 on 2023-01-19 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_owner_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('house_no', models.CharField(max_length=20)),
                ('family_member', models.CharField(max_length=20)),
                ('no_of_vihical', models.CharField(max_length=20)),
                ('pic', models.FileField(upload_to='media/images')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
