# Generated by Django 4.1.3 on 2023-01-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_member_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.FileField(default='media/images/set.png.png', upload_to='media/images/'),
        ),
    ]
