# Generated by Django 4.1.3 on 2023-01-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_member_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='nil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(default='set.png.png', upload_to='media/images/')),
            ],
        ),
    ]
