# Generated by Django 4.1.3 on 2023-01-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_nil_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nil',
        ),
    ]
