# Generated by Django 4.1.3 on 2023-01-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delete_nil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='contact_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
