# Generated by Django 4.1.3 on 2023-02-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_member_age_alter_member_contact_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_name', models.CharField(max_length=30)),
                ('notice_topic', models.CharField(max_length=100)),
                ('notice_date', models.DateTimeField()),
            ],
        ),
    ]
