# Generated by Django 4.1.3 on 2023-02-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_topic',
            field=models.TextField(),
        ),
    ]
