# Generated by Django 4.1.3 on 2023-02-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_notice_notice_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('house_no', models.CharField(max_length=20)),
                ('family_member', models.CharField(max_length=20)),
                ('pic', models.FileField(default='media/images/s1.jpg', upload_to='media/images/')),
            ],
        ),
    ]
