# Generated by Django 4.1.3 on 2023-02-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_sell_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell_home',
            old_name='gender',
            new_name='address',
        ),
    ]
