# Generated by Django 4.1.3 on 2022-12-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
