# Generated by Django 4.1.3 on 2022-12-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_chairman_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairman',
            name='lastname',
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=30)),
                ('family_member', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('job_loction', models.CharField(max_length=30)),
                ('block_number', models.CharField(max_length=30)),
                ('house_number', models.CharField(max_length=30)),
                ('no_of_vehicle', models.CharField(max_length=30)),
                ('pic', models.FileField(default='media/set.png.png', upload_to='media/images/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
