# Generated by Django 4.1.3 on 2022-12-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_event_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.FileField(upload_to='media/images/'),
        ),
    ]
