# Generated by Django 4.1.3 on 2022-12-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_member_pic_alter_notice_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='pic',
            field=models.FileField(blank=True, default='media/set.png.png', null=True, upload_to='media/images/'),
        ),
    ]
